// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type File struct {
	ID      int64
	Path    string
	Lang    string
	Hash    string
	Summary string
}

type Method struct {
	ID        int64
	ParentID  int64
	Name      string
	Signature string
	Kind      string
}

type Relation struct {
	ID       int64
	FromID   int64
	ToID     int64
	EdgeKind string
}

type Symbol struct {
	ID        int64
	Name      string
	Kind      string
	Package   string
	File      string
	Signature string
}
