// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const deleteAllFiles = `-- name: DeleteAllFiles :exec
DELETE FROM files
`

func (q *Queries) DeleteAllFiles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFiles)
	return err
}

const deleteAllMethods = `-- name: DeleteAllMethods :exec
DELETE FROM methods
`

func (q *Queries) DeleteAllMethods(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMethods)
	return err
}

const deleteAllRelations = `-- name: DeleteAllRelations :exec
DELETE FROM relations
`

func (q *Queries) DeleteAllRelations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRelations)
	return err
}

const deleteAllSymbols = `-- name: DeleteAllSymbols :exec
DELETE FROM symbols
`

func (q *Queries) DeleteAllSymbols(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSymbols)
	return err
}

const getCallersOf = `-- name: GetCallersOf :many
SELECT s.name
FROM relations r
JOIN symbols s ON s.id = r.from_id
WHERE r.to_id = ? AND r.edge_kind = 'call'
ORDER BY s.name
`

func (q *Queries) GetCallersOf(ctx context.Context, toID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCallersOf, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallsFrom = `-- name: GetCallsFrom :many
SELECT s.name
FROM relations r
JOIN symbols s ON s.id = r.to_id
WHERE r.from_id = ? AND r.edge_kind = 'call'
ORDER BY s.name
`

func (q *Queries) GetCallsFrom(ctx context.Context, fromID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCallsFrom, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImplementationsOf = `-- name: GetImplementationsOf :many
SELECT s.name
FROM relations r
JOIN symbols s ON s.id = r.to_id
WHERE r.from_id = ? AND r.edge_kind = 'implement'
ORDER BY s.name
`

func (q *Queries) GetImplementationsOf(ctx context.Context, fromID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getImplementationsOf, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMethodsOf = `-- name: GetMethodsOf :many
SELECT name
FROM methods
WHERE parent_id = ?
ORDER BY name
`

func (q *Queries) GetMethodsOf(ctx context.Context, parentID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMethodsOf, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferencesOf = `-- name: GetReferencesOf :many
SELECT s.name
FROM relations r
JOIN symbols s ON s.id = r.from_id
WHERE r.to_id = ? AND r.edge_kind = 'ref'
ORDER BY s.name
`

func (q *Queries) GetReferencesOf(ctx context.Context, toID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getReferencesOf, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTypeUsesFrom = `-- name: GetTypeUsesFrom :many
SELECT s.name
FROM relations r
JOIN symbols s ON s.id = r.to_id
WHERE r.from_id = ? AND r.edge_kind = 'ref'
ORDER BY s.name
`

func (q *Queries) GetTypeUsesFrom(ctx context.Context, fromID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTypeUsesFrom, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO files (path, lang, hash, summary)
VALUES (?, ?, ?, ?)
`

type InsertFileParams struct {
	Path    string
	Lang    string
	Hash    string
	Summary string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.Path,
		arg.Lang,
		arg.Hash,
		arg.Summary,
	)
	return err
}

const insertMethod = `-- name: InsertMethod :exec
INSERT INTO methods (parent_id, name, signature, kind)
VALUES (?, ?, ?, ?)
`

type InsertMethodParams struct {
	ParentID  int64
	Name      string
	Signature string
	Kind      string
}

func (q *Queries) InsertMethod(ctx context.Context, arg InsertMethodParams) error {
	_, err := q.db.ExecContext(ctx, insertMethod,
		arg.ParentID,
		arg.Name,
		arg.Signature,
		arg.Kind,
	)
	return err
}

const insertRelation = `-- name: InsertRelation :exec
INSERT INTO relations (from_id, to_id, edge_kind)
VALUES (?, ?, ?)
`

type InsertRelationParams struct {
	FromID   int64
	ToID     int64
	EdgeKind string
}

func (q *Queries) InsertRelation(ctx context.Context, arg InsertRelationParams) error {
	_, err := q.db.ExecContext(ctx, insertRelation, arg.FromID, arg.ToID, arg.EdgeKind)
	return err
}

const insertSymbol = `-- name: InsertSymbol :exec
INSERT INTO symbols (id, name, kind, package, file, signature)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSymbolParams struct {
	ID        int64
	Name      string
	Kind      string
	Package   string
	File      string
	Signature string
}

func (q *Queries) InsertSymbol(ctx context.Context, arg InsertSymbolParams) error {
	_, err := q.db.ExecContext(ctx, insertSymbol,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Package,
		arg.File,
		arg.Signature,
	)
	return err
}

const listSymbols = `-- name: ListSymbols :many
SELECT id, name, kind, package, file, signature
FROM symbols
ORDER BY name
`

func (q *Queries) ListSymbols(ctx context.Context) ([]Symbol, error) {
	rows, err := q.db.QueryContext(ctx, listSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Symbol
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Package,
			&i.File,
			&i.Signature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
